version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "5505:5000"
    depends_on:
      - db
    networks:
      - internal
      - default
  db:
    image: mysql:5.7
    volumes:
      - db_data_renewtest:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: alperslist
    networks:
      - internal


networks:
  default:
  internal:
    internal: true

volumes:
  db_data_renewtest: